### PR TITLE
SELinux policies

### PR DESCRIPTION
**Pull request by dd-dreams**

### CODE REVIEW

**Comment by dd-dreams** [comment]
Would love some feedback.

**Comment by sysxda** [comment]
feedback : keep proper authorship

**Comment by dd-dreams** [comment]
@sysxda You mean giving credit?

**Comment by sysxda** [comment]
> @sysxda You mean giving credit?

I mean - google how to use git cherry-pick and other commands to keep original commit authorship

**Comment by dd-dreams** [comment]
> > @sysxda You mean giving credit?
> 
> I mean - google how to use git cherry-pick and other commands to keep original commit authorship

using git `cherry-pick` could mess up the code since some changes had been made since then. for example: in the first commit I used flawedworld commit on 12.1 branch, but he had to remove another line where here in this branch it doesn't exist. most of the features commits in 12.1 require refactoring but the commits here are inspired by them.

**Comment by thestinger** [comment]
Can you please help with reviewing the changes that I merged instead?

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/platform_system_sepolicy/pull/42

**Comment by dd-dreams** [comment]
@thestinger curious, what was wrong with this?

**Comment by thestinger** [comment]
@dd-dreams There were some unnecessary changes being made and you can see that a complete port was done by one of the core developers, see #42.

**Comment by dd-dreams** [comment]
@thestinger How would you suggest to avoid those unnecessary changes? I tried to find docs for these SELinux policies
but couldn't find.

**Comment by dd-dreams** [comment]
@thestinger what unnecessary changes?

**Pull request closed without merging**
